package com.saj.api.modules.process.domain.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TypeMovements {

    CASE_CREATED("CRIACAO_PROCESSO"),
    DISTRIBUTION("DISTRIBUICAO"),
    REDISTRIBUTION("REDISTRIBUICAO"),
    TRANSFERRED("TRANSFERENCIA"),

    INITIAL_PETITION("PETICAO_INICIAL"),
    INTERMEDIATE_PETITION("PETICAO_INTERMEDIARIA"),
    CONTESTATION("CONTESTACAO"),
    APPEAL("APELACAO"),
    COUNTER_ARGUMENTS("CONTRARRAZOES"),
    ATTACHMENT("JUNTADA_DOCUMENTO"),
    MANIFESTATION("MANIFESTACAO"),

    DISPATCH("DESPACHO"),
    INTERLOCUTORY_DECISION("DECISAO_INTERLOCUTORIA"),
    SENTENCE("SENTENCA"),
    COLLEGIATE_DECISION("DECISAO_COLEGIADA"),
    SINGLE_JUDGE_DECISION("DECISAO_MONOCRATICA"),

    CONCILIATION_HEARING("AUDIENCIA_CONCILIACAO"),
    INSTRUCTION_HEARING("AUDIENCIA_INSTRUCAO"),
    HEARING_HELD("AUDIENCIA_REALIZADA"),
    HEARING_CANCELLED("AUDIENCIA_CANCELADA"),
    HEARING_RESCHEDULED("AUDIENCIA_REAGENDADA"),

    SUMMONS("CITACAO"),
    SUBPOENA("INTIMACAO"),
    DEADLINE_OPENED("PRAZO_ABERTO"),
    DEADLINE_CLOSED("PRAZO_ENCERRADO"),
    DEADLINE_SUSPENDED("PRAZO_SUSPENSO"),

    SUBMITTED_TO_JUDGE("CONCLUSO_JUIZ"),
    REFERRED_TO_DA("ENCAMINHADO_DA"),
    REFERRED_TO_EXPERT("ENCAMINHADO_PERITO"),
    EXPERT_EXAMINATION("PERICIA"),
    DUE_DILIGENCE("DILIGENCIA"),

    ENFORCEMENT_STARTED("EXECUCAO_INICIADA"),
    ASSET_SEIZURE("PENHORA"),
    PUBLIC_AUCTION("LEILAO"),
    PAYMENT("PAGAMENTO"),
    ENFORCEMENT_DISMISSED("EXECUCAO_EXTINTA"),

    ARCHIVED("ARQUIVADO"),
    DISMISSED_WITHOUT_MERIT("EXTINTO_SEM_MERITO"),
    DISMISSED_WITH_MERIT("EXTINTO_COM_MERITO"),
    SETTLEMENT("ACORDO"),
    WITHDRAWAL("DESISTENCIA"),
    FINAL_JUDGMENT("TRANSITO_EM_JULGADO"),

    COMMENT("COMENTARIO"),
    CLIENT_VIEWED("CLIENTE_VISUALIZOU"),
    SUSPENDED("SUSPENSO"),
    REACTIVATED("REATIVADO");


    private final String value;
}
